eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        predicates:
           - Path=/users/**
        uri: lb://USER-SERVICE
        filters:
        - name: CircuitBreaker
          args:
            name : USER-SERVICE
            fallbackuri : forward:/userServiceFallBack
      - id: DEPARTMENT-SERVICE
        predicates:
           - Path=/departments/**
        uri: lb://DEPARTMENT-SERVICE
        filters:
        - name: CircuitBreaker
          args:
            name : DEPARTMENT-SERVICE
            fallbackuri : forward:/departmentServiceFallBack
            
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream